### ISSUE TITLE
Hourly crashes when selected station does not provide hourly data

### ISSUE THREAD

**Issue by MarieCurie13** [meteostat/meteostat-python#15]
If a station Id, for which no hourly data exist (e.g. ...09161, 09177, 09186... selected from full.json), is used in e.g.
`    data = Hourly(stations=stationId, start=start, end=end, timezone='Europe/Berlin')` 
Hourly crashes, with producing this traceback dump:

+++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meteostat/hourly.py", line 168, in __init__
    self._get_data(self._stations)
  File "/usr/local/lib/python3.7/site-packages/meteostat/hourly.py", line 122, in _get_data
    'UTC', level='time').tz_convert(
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 9650, in tz_localize
    ax = ax.set_levels(new_level, level=level)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 830, in set_levels
    if is_list_like(levels[0]):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/extension.py", line 215, in __getitem__
    result = self._data[key]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/arrays/datetimelike.py", line 538, in __getitem__
    result = self._data[key]
IndexError: index 0 is out of bounds for axis 0 with size 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "t.py", line 18, in <module>
    data = Hourly(stations=stationId, start=start, end=end, timezone='Europe/Berlin')
  File "/usr/local/lib/python3.7/site-packages/meteostat/hourly.py", line 170, in __init__
    raise Exception('Cannot read hourly data') from read_error
Exception: Cannot read hourly data`
+++++++++++++++++++++++++++++++

It would be good if in such a case an empty frame would be returned which could be handled via the `data.empty` method.

**Comment by clampr** [comment]
Fixed in #19.
